import { KnotData, DayContent, DayType, MockUser } from '@/types';

export const KNOTS: KnotData[] = [
  {
    id: 1,
    name: 'Being Seen & Heard',
    fullName: 'Knot of Being Seen & Heard',
    theme: 'What You Wish Others Knew',
    movement: 'Awareness',
    movementNumber: 1,
    knotsTruth: 'You are not invisible. What you are carrying is real, and you are allowed to let it be witnessed.',
    anchorQuestions: {
      why: [
        'Why am I allowed to let what I carry be seen and witnessed by others?',
        'Why does being seen matter as much as the care I give?',
        'Why is my story worth telling, even when I feel like a burden?',
        'Why does vulnerability in caregiving take more strength than silence?',
        'Why am I allowed to ask for witness rather than solutions?',
        'Why is invisibility a cost I no longer have to pay alone?',
        'Why does being witnessed change the weight of what I carry?',
      ],
      what: [
        'What am I carrying right now that deserves to be witnessed?',
        'What part of my caregiving story have I been afraid to let others see?',
        'What would change if I allowed one person to truly see my experience?',
        'What have I been minimizing about my own struggle?',
        'What do I wish someone understood about my daily reality?',
        'What feelings have I kept hidden because I thought no one would understand?',
        'What would it mean to stop pretending everything is fine?',
      ],
      where: [
        'Where can I allow myself to be truly seen today?',
        'Where in my life is there someone safe enough to witness my truth?',
        'Where have I been hiding the hardest parts of this journey?',
        'Where could sharing even a small piece of my reality bring relief?',
        'Where am I carrying something that was never meant to be carried alone?',
        'Where in my day can I create a moment of honest connection?',
        'Where do I feel most invisible, and what would it take to step into the light there?',
      ],
    },
  },
  {
    id: 2,
    name: 'Grace',
    fullName: 'Knot of Grace',
    theme: 'Permission to Feel Everything',
    movement: 'Awareness',
    movementNumber: 1,
    knotsTruth: "You don't have to earn the right to feel. Everything you're feeling is allowed. All of it.",
    anchorQuestions: {
      why: [
        "Why am I allowed to feel everything without earning that right?",
        'Why does grace extend to the feelings I am most ashamed of?',
        'Why is it an act of love to let myself feel, rather than suppress?',
        'Why does numbness cost more than feeling, over time?',
        'Why am I allowed to be both devoted and exhausted at the same time?',
        'Why is feeling fully an act of courage rather than weakness?',
        'Why does permission to feel change how I show up for others?',
      ],
      what: [
        'What feelings have I been trying to earn the right to feel?',
        'What emotion have I been avoiding that is asking to be acknowledged?',
        'What would I feel if I stopped judging my feelings as right or wrong?',
        'What part of my emotional experience have I been calling "too much"?',
        'What feelings have I been keeping private because they seemed unacceptable?',
        'What becomes available when I stop managing my emotions and start honoring them?',
        'What do I need to feel today that I have been postponing?',
      ],
      where: [
        'Where can I give myself permission to simply feel today?',
        'Where in my life have I been performing okayness instead of living it?',
        'Where am I holding feelings at bay that are asking to move through me?',
        'Where could softening — just slightly — create more space inside me?',
        'Where do I feel most contracted emotionally, and what might open if I allowed it?',
        'Where in my body am I carrying something my heart has not yet spoken?',
        'Where can I be gentle with myself about the complexity of what I feel?',
      ],
    },
  },
  {
    id: 3,
    name: 'Emotional Release',
    fullName: 'Knot of Emotional Release',
    theme: 'Honor the Feeling, Protect the Love',
    movement: 'Awareness',
    movementNumber: 1,
    knotsTruth: 'Honor the feeling. Protect the love. Both belong to you, and both are possible.',
    anchorQuestions: {
      why: [
        'Why am I allowed to honor my feelings while still protecting the love that drives my caregiving?',
        'Why does releasing emotion honor rather than betray the relationship I am in?',
        'Why is unexpressed emotion a cost the body eventually collects?',
        'Why does what I feel not define what I do or who I love?',
        'Why is emotional release a form of tending the relationship, not threatening it?',
        'Why am I allowed to feel frustrated, angry, or depleted without being a bad caregiver?',
        'Why does honoring the feeling allow more love to flow, not less?',
      ],
      what: [
        'What feelings need honoring that I have been holding back?',
        'What emotion have I been calling "inappropriate" that is simply human?',
        'What have I been afraid my true feelings would say about me?',
        'What am I carrying emotionally that needs to be released before it hardens?',
        'What would I say if I knew my feelings were safe to speak?',
        'What has been simmering beneath the surface of my daily caregiving?',
        'What becomes possible when I honor the feeling without acting it out?',
      ],
      where: [
        'Where in my life am I ready to release what I have been carrying?',
        'Where can I find a safe space to let my emotions move through me?',
        'Where have I been suppressing feelings that deserve acknowledgment?',
        'Where in my body do I feel the stored weight of unexpressed emotion?',
        'Where can I begin to honor what is true without causing harm?',
        'Where am I most afraid to feel fully, and why?',
        'Where in my week can I create intentional space for emotional release?',
      ],
    },
  },
  {
    id: 4,
    name: 'Releasing Expectations',
    fullName: 'Knot of Releasing Expectations',
    theme: 'Letting Go of the Perfect Caregiver',
    movement: 'Awareness',
    movementNumber: 1,
    knotsTruth: 'There is no perfect caregiver. There is only the one who keeps showing up.',
    anchorQuestions: {
      why: [
        'Why am I allowed to release the expectation of being a perfect caregiver?',
        'Why does perfection make caregiving unsustainable over time?',
        'Why is showing up imperfectly still an act of profound love?',
        'Why do the standards I hold myself to often exceed what I would ask of anyone else?',
        'Why is releasing impossible expectations an act of wisdom, not resignation?',
        'Why does good enough sometimes mean more than perfect ever could?',
        'Why am I allowed to do my best without requiring it to be flawless?',
      ],
      what: [
        'What expectations of myself am I ready to lay down?',
        'What impossible standard have I been quietly holding myself to?',
        'What would caregiving look like if I released the need to do it perfectly?',
        'What have I been criticizing myself for that any reasonable person would struggle with?',
        'What expectations were given to me rather than chosen by me?',
        'What becomes lighter when I let go of perfection as the measure of love?',
        'What do I tell myself I should have done that no one could have done better?',
      ],
      where: [
        'Where in my caregiving am I ready to embrace good enough instead of perfect?',
        'Where am I exhausting myself chasing a standard that was never realistic?',
        'Where could releasing one expectation today create more room to breathe?',
        'Where does the voice of perfectionism show up most loudly in my daily life?',
        'Where have I already exceeded what anyone could ask — without giving myself credit?',
        'Where am I withholding grace from myself that I freely offer to others?',
        'Where would releasing an expectation allow me to be more present to what matters?',
      ],
    },
  },
  {
    id: 5,
    name: 'Humor',
    fullName: 'Knot of Humor',
    theme: 'Laughter as a Life Preserver',
    movement: 'Awareness',
    movementNumber: 1,
    knotsTruth: 'Laughter cracks the grief wide open and lets in light. You deserve that light. Please read that again. You deserve that light.',
    anchorQuestions: {
      why: [
        'Why am I allowed to experience moments of laughter even in the middle of hard seasons?',
        'Why does humor not diminish the seriousness of what I carry?',
        'Why is laughter a legitimate form of healing, not an escape from it?',
        'Why do the people I care for often need my laughter as much as my tears?',
        'Why am I allowed to find something funny without it meaning I do not care deeply?',
        'Why does levity, when it comes naturally, serve both of us?',
        'Why is joy and grief not in opposition — can they both exist in the same breath?',
      ],
      what: [
        'What moments of lightness have already found me, even in this season?',
        'What made me laugh recently, and what did that moment give me?',
        'What would I allow myself to find funny if I stopped feeling guilty about it?',
        'What humor has existed between me and the person I care for that I treasure?',
        'What absurdity in caregiving life deserves to be acknowledged with a smile?',
        'What would laughter restore in me today, even briefly?',
        'What funny memory am I holding that I could return to when I need light?',
      ],
      where: [
        'Where in my life can I allow even a small moment of laughter or ease today?',
        'Where has lightness been trying to reach me that I have been too busy to notice?',
        'Where could I invite humor into an ordinary moment of my caregiving day?',
        'Where am I holding myself too tightly to allow joy to slip through?',
        'Where in my relationships is there room to share a laugh that would do us both good?',
        'Where could a lighter moment become a memory I will carry forward with love?',
        'Where is laughter already quietly present in my life, waiting to be fully received?',
      ],
    },
  },
  {
    id: 6,
    name: 'Joy',
    fullName: 'Knot of Joy',
    theme: 'Finding Joy in the Smallest Moments',
    movement: 'Embodiment',
    movementNumber: 2,
    knotsTruth: "Joy is not gone, she's waiting to be noticed. Not later. Not when it's over. Now.",
    anchorQuestions: {
      why: [
        'Why am I able to create and experience moments of Joy even in the middle of this season?',
        'Why does noticing joy not mean pretending the hard parts are not real?',
        'Why do small moments of joy matter as much as large ones?',
        'Why does joy serve both me and the one I care for?',
        'Why am I allowed to feel alive even in a season marked by loss?',
        'Why is cultivating joy an act of resistance to despair?',
        'Why does joy, even when small, signal something important about resilience?',
      ],
      what: [
        'What small moments of Joy are already available to me, right now in this season?',
        'What brings me even a flicker of delight that I have been overlooking?',
        'What would I notice today if I were looking for beauty rather than burden?',
        'What recent moment held something sweet, even briefly?',
        'What sensory experience — light, sound, warmth, taste — could I savor today?',
        'What small thing has made me smile this week that I did not fully receive?',
        'What does joy feel like in my body, and where does it live?',
      ],
      where: [
        'Where in my day can I gently invite more connection, lightness, or meaning?',
        'Where is joy already quietly present in my life, waiting to be acknowledged?',
        'Where could I pause today, even for one minute, to let something good land?',
        'Where am I rushing past beauty because I am focused on what needs doing?',
        'Where in my caregiving day is there a moment that could become a small ritual of joy?',
        'Where can I create space for delight, even in a season that feels heavy?',
        'Where does joy tend to find me when I am not looking for it?',
      ],
    },
  },
  {
    id: 7,
    name: 'Time Alone',
    fullName: 'Knot of Time Alone',
    theme: 'Solitude as Sacred Space',
    movement: 'Embodiment',
    movementNumber: 2,
    knotsTruth: "Solitude is soul-care. You don't have to earn it. You just get to claim it.",
    anchorQuestions: {
      why: [
        'Why am I allowed to claim time alone as something sacred and restorative?',
        'Why does solitude not mean abandonment of the one I care for?',
        'Why is replenishing myself an act of love, not selfishness?',
        'Why do I return to caregiving better when I have first returned to myself?',
        'Why does needing quiet not mean something is wrong with me?',
        'Why is solitude as essential as sleep or nourishment?',
        'Why am I allowed to be alone without having to justify or explain it?',
      ],
      what: [
        'What does the quiet make possible in me when I allow space for it?',
        'What happens inside me when I am finally alone and still?',
        'What have I been putting off for myself because I felt I did not deserve the time?',
        'What kind of solitude restores me most — movement, stillness, nature, silence?',
        'What do I hear when the noise of caregiving quiets, even briefly?',
        'What part of me comes back online when I have time that is just mine?',
        'What would I do with even fifteen minutes entirely to myself?',
      ],
      where: [
        'Where in my days can I create even a small sanctuary to return to myself?',
        'Where do I feel most like myself, and how often am I choosing to go there?',
        'Where could I carve out quiet in a way that feels realistic, not aspirational?',
        'Where has the noise of caregiving followed me even into spaces meant for rest?',
        'Where in my week is there an honest opportunity to be alone that I keep skipping?',
        "Where could I begin to protect my solitude the way I protect everyone else's needs?",
        'Where am I most able to hear myself think, breathe, and simply be?',
      ],
    },
  },
  {
    id: 8,
    name: 'Sacred Moments',
    fullName: 'Knot of Sacred Moments',
    theme: 'Creating & Savoring Them',
    movement: 'Embodiment',
    movementNumber: 2,
    knotsTruth: "Sacredness isn't found in perfection. It's woven into presence. Small moments in time become sacred moments in memory — for you, and for the one receiving your care.",
    anchorQuestions: {
      why: [
        'Why am I able to recognize sacredness in ordinary moments of this journey?',
        'Why do small moments become the ones we remember most?',
        'Why is presence more powerful than perfection when creating sacred memories?',
        'Why do the simple, quiet moments between us carry more weight than the grand gestures?',
        'Why am I allowed to name something sacred even when it is imperfect or incomplete?',
        'Why does noticing the sacred change the quality of time, not just the meaning of it?',
        'Why is this ordinary moment, this one right now, worth honoring?',
      ],
      what: [
        'What moments of beauty or connection have I been living that deserve to be noticed more fully?',
        'What has happened recently that was quietly extraordinary, even if I moved past it quickly?',
        'What moment from this caregiving season do I want to hold on to?',
        'What simple act between me and the one I care for has held more tenderness than I acknowledged?',
        'What would I call sacred if I were paying closer attention?',
        'What ordinary moment today could become a sacred memory I carry forward?',
        'What am I witnessing in this season that few others will ever understand?',
      ],
      where: [
        'Where in my everyday life is the sacred quietly present, waiting to be recognized?',
        'Where do sacred moments tend to find me when I slow down enough to receive them?',
        'Where could I be more present today in a way that turns ordinary into meaningful?',
        'Where has something beautiful happened in my caregiving that I dismissed as routine?',
        'Where could I create a small ritual that honors what is happening in this season?',
        'Where am I moving too fast to notice what is asking to be remembered?',
        'Where in my home, my routine, or my relationship is the sacred already woven in?',
      ],
    },
  },
  {
    id: 9,
    name: 'Ritual',
    fullName: 'Knot of Ritual',
    theme: 'Anchoring It In',
    movement: 'Embodiment',
    movementNumber: 2,
    knotsTruth: "You don't need to add more to your plate. Just infuse what's already there with presence. That's a ritual. And that's enough.",
    anchorQuestions: {
      why: [
        'Why am I able to create sacred rhythm through simple rituals in daily life?',
        'Why does a ritual not require elaborate preparation or perfect conditions?',
        'Why does intention transform an ordinary act into something that anchors me?',
        'Why does having a ritual matter when everything else feels unpredictable?',
        'Why is rhythm as essential as rest when sustaining a caregiving life?',
        'Why am I allowed to make something simple into something sacred?',
        'Why do rituals serve as signals to my nervous system that I am safe and cared for?',
      ],
      what: [
        'What ordinary acts in my days could become more meaningful through intention?',
        'What do I already do each day that could be treated as a small sacred ritual?',
        'What ritual, however tiny, gives me a sense of grounding?',
        'What activity, when done with full presence, makes me feel most like myself?',
        'What would I add to my day if I knew a simple ritual counted as self-care?',
        'What has been missing from my days that a small ritual could provide?',
        'What ordinary moment could become a daily anchor I return to intentionally?',
      ],
      where: [
        'Where in my routines can I create small rituals that anchor me in presence?',
        'Where in my day am I already moving through something that could become a ritual?',
        'Where could adding intention to something I already do create more steadiness?',
        'Where do I feel most grounded, and how could I return there more intentionally?',
        'Where in my week could I build in one small act that is only for me?',
        'Where have I been trying to add more, when what I needed was to be more present to less?',
        'Where does my body feel most settled, and how could I ritualize returning to that feeling?',
      ],
    },
  },
  {
    id: 10,
    name: 'Permission',
    fullName: 'Knot of Permission',
    theme: 'Learning to Receive Help Without Guilt',
    movement: 'Embodiment',
    movementNumber: 2,
    knotsTruth: "The Knot of Permission does not make your load lighter. But it makes it bearable. It helps you honor your own struggle — and that changes everything.",
    anchorQuestions: {
      why: [
        'Why am I able to trust myself to honor what I need without waiting for permission?',
        'Why does needing help not diminish what I have already given?',
        'Why is receiving as much an act of love as giving?',
        'Why do I get to decide what I need without justifying it to anyone?',
        'Why does asking for help honor the people who want to support me?',
        'Why is self-permission more powerful than waiting for someone else to grant it?',
        'Why am I allowed to say yes to support without owing an explanation?',
      ],
      what: [
        'What have I been denying myself that I am ready to allow?',
        'What would I say yes to today if I stopped waiting for permission?',
        'What support have I refused because I felt I did not deserve it or should manage alone?',
        'What need have I been quietly carrying that deserves to be spoken?',
        'What is one thing I could allow myself today that I usually withhold?',
        'What would change if I treated my own needs as worthy of the same attention I give others?',
        'What am I ready to receive that I have been blocking?',
      ],
      where: [
        'Where in my life am I ready to grant myself more space, rest, truth, or support?',
        'Where am I still waiting for someone to tell me it is okay?',
        'Where could accepting help today make tomorrow more sustainable?',
        'Where have I been the last to receive in a situation that was supposed to include me?',
        'Where in my caregiving am I depleting myself because I refuse support?',
        'Where could I say yes today to something I would normally decline out of guilt?',
        'Where is self-permission already trying to reach me, and what is in the way?',
      ],
    },
  },
  {
    id: 11,
    name: 'Self-Compassion',
    fullName: 'Knot of Self-Compassion',
    theme: 'Treating Yourself Like Someone You Love',
    movement: 'Integration',
    movementNumber: 3,
    knotsTruth: 'The compassion you so freely give to others was always meant for you too.',
    anchorQuestions: {
      why: [
        'Why am I deserving of the same compassion I so freely give to others?',
        'Why does self-compassion not compete with the care I offer — it sustains it?',
        'Why is speaking kindly to myself not indulgent, but necessary?',
        'Why do the standards I hold myself to rarely reflect what I would ask of someone I love?',
        'Why does the harshest voice in my head deserve to be answered with kindness?',
        'Why am I allowed to forgive myself for the moments I could not do better?',
        'Why does self-compassion make me a more present and sustainable caregiver?',
      ],
      what: [
        'What have I done today, however small, that was genuinely enough?',
        'What would I say to a dear friend in my exact situation right now?',
        'What critical thought about myself is ready to be answered with gentleness?',
        'What do I deserve to hear today that I have not been saying to myself?',
        'What accomplishment have I dismissed today that deserves acknowledgment?',
        'What part of my struggle am I judging when I could be honoring it instead?',
        'What would self-compassion look like in practice for me, today?',
      ],
      where: [
        'Where am I being harder on myself than I would ever be on someone I love?',
        'Where does the inner critic show up most loudly in my caregiving life?',
        'Where could I replace self-judgment with curiosity or kindness today?',
        'Where am I withholding grace from myself that I would freely offer a friend?',
        'Where in my thinking is there room to introduce a softer, truer narrative?',
        'Where do I most need to hear "you are doing enough" — and can I offer that to myself?',
        'Where is self-compassion trying to reach me, and what keeps pushing it away?',
      ],
    },
  },
  {
    id: 12,
    name: 'Self-Care',
    fullName: 'Knot of Self-Care',
    theme: 'Caregiving Is Not Your Whole Identity',
    movement: 'Integration',
    movementNumber: 3,
    knotsTruth: "You can't pour from an empty cup. Refill yourself — not just for them, but for you.",
    anchorQuestions: {
      why: [
        'Why am I worthy of tending my own well-being with the same care I offer others?',
        'Why does caring for myself not make me less devoted to the person I care for?',
        'Why is self-care an investment in the sustainability of my caregiving?',
        'Why am I a person, not just a function — and why does that matter right now?',
        'Why does my identity extend beyond the role of caregiver?',
        'Why is self-care not a luxury I earn but a necessity I deserve?',
        'Why does who I am outside of caregiving deserve to be tended and honored?',
      ],
      what: [
        'What forms of nourishment am I needing that deserve more attention right now?',
        'What would I do for myself today if I believed I deserved to be cared for?',
        'What part of my identity beyond caregiving have I been neglecting?',
        'What does my body, mind, or spirit need most right now?',
        'What one act of self-care is available to me today that I could choose?',
        'What have I been telling myself I will do for myself "when things settle down"?',
        'What would full-spectrum self-care look like for someone in my situation?',
      ],
      where: [
        'Where in my days can I create small acts of restoration that help sustain me?',
        'Where am I last on my own list, and what would it take to move myself up?',
        'Where does caregiving end and where does my own life begin?',
        'Where have I stopped doing things that once brought me joy or felt like me?',
        'Where could one small act of self-care today create more capacity tomorrow?',
        'Where am I most depleted, and what kind of care would reach that place?',
        'Where in my week could I protect at least one hour that is fully mine?',
      ],
    },
  },
  {
    id: 13,
    name: 'Boundaries',
    fullName: 'Knot of Boundaries',
    theme: 'Boundaries Are Not Betrayal',
    movement: 'Integration',
    movementNumber: 3,
    knotsTruth: "You are not being selfish for needing space. You are wise for honoring your limits. Boundaries don't end love — they protect it.",
    anchorQuestions: {
      why: [
        'Why am I able to honor my limits without making it mean I care any less?',
        'Why does a boundary protect the relationship rather than threaten it?',
        'Why is saying no sometimes the most loving thing I can do?',
        'Why do I deserve to have needs that are honored, not only managed?',
        'Why does caregiving without limits eventually deplete the love that fuels it?',
        'Why is knowing my limits an act of self-knowledge, not selfishness?',
        'Why am I allowed to protect my own well-being as part of the care I give?',
      ],
      what: [
        'What becomes possible when I protect my energy instead of constantly giving it away?',
        'What boundary have I been afraid to name or hold?',
        'What am I silently absorbing that a healthy limit could release?',
        'What would change in my caregiving if I honored my own limits more consistently?',
        'What does saying yes when I mean no cost me over time?',
        'What is one thing I could decline today that would restore something in me?',
        'What have I been giving from depletion that deserves to come from fullness instead?',
      ],
      where: [
        'Where in my life am I being invited to choose sustainability over overextension?',
        'Where do I feel most stretched, and what boundary might bring relief there?',
        'Where have I been saying yes when my whole body was saying no?',
        'Where is there a limit I have been afraid to communicate?',
        'Where could one clear boundary today make the rest of the week more livable?',
        'Where am I overgiving in ways that are beginning to breed resentment?',
        'Where is the invitation to protect love by protecting yourself?',
      ],
    },
  },
  {
    id: 14,
    name: 'Witnessing',
    fullName: 'Knot of Witnessing',
    theme: 'Meeting Life With Presence Instead of Control',
    movement: 'Integration',
    movementNumber: 3,
    knotsTruth: "You don't have to fix everything. Your presence is often enough.",
    anchorQuestions: {
      why: [
        'Why am I able to trust presence, even when I am not fixing or controlling what is unfolding?',
        'Why does witnessing require more courage than solving?',
        'Why does the person I care for sometimes need my steady presence more than my intervention?',
        'Why is it enough to simply show up without having to make it better?',
        'Why does releasing the need to control create more space for connection?',
        'Why is bearing witness to suffering a profound act of love?',
        'Why am I allowed to not have answers and still be exactly what is needed?',
      ],
      what: [
        'What becomes possible when I meet difficult moments with curiosity instead of reactivity?',
        'What am I trying to fix that may simply need to be witnessed?',
        'What happens when I release the need to have the right response and simply stay present?',
        'What would I notice about this moment if I were fully here for it?',
        'What does presence feel like in my body, and how do I return to it?',
        'What am I missing when I am focused on managing rather than being?',
        'What would it mean to witness myself with the same patience I offer others?',
      ],
      where: [
        'Where in my life am I being invited to witness more — and control less?',
        'Where is the urge to fix getting in the way of simply being there?',
        'Where could releasing one attempt at control today create more peace?',
        'Where am I exhausting myself trying to manage outcomes that are not mine to manage?',
        'Where does presence — just mine, just here — matter more than solutions?',
        'Where in my relationship am I being asked to witness rather than rescue?',
        'Where would softening my grip on outcomes allow more love to flow?',
      ],
    },
  },
  {
    id: 15,
    name: 'Surrender',
    fullName: 'Knot of Surrender',
    theme: 'Let the Grief Come',
    movement: 'Integration',
    movementNumber: 3,
    knotsTruth: 'They are still here. And you are already grieving. Both of those things are true. Both of them are allowed.',
    openingQuote: 'Surrender is not defeat. It is wisdom. It is the recognition that some things cannot be carried through force…only through Grace.',
    anchorQuestions: {
      why: [
        'Why am I able to trust what grief is asking me to feel, rather than resist it?',
        'Why does grief in caregiving begin before the loss we fear?',
        'Why is anticipatory grief a form of love, not weakness?',
        'Why is it safe to grieve what is changing even while they are still here?',
        'Why does surrender open something in me that resistance keeps closed?',
        'Why am I allowed to mourn the person they were becoming alongside caring for who they are now?',
        'Why does grief, when honored, eventually move — rather than stay?',
      ],
      what: [
        'What might become possible when I let grief move through me instead of holding it back?',
        'What am I grieving right now that I have not fully named?',
        'What loss — of the person they were, of the life I imagined, of my own freedom — is asking to be honored?',
        'What happens inside me when I stop fighting the grief and allow it space?',
        'What would I say to my grief if I treated it as something wise rather than something wrong?',
        'What is grief trying to tell me about what I love and what matters most?',
        'What would it mean to grieve well in this season — for myself and for them?',
      ],
      where: [
        'Where in this season am I being invited to soften, surrender, and let love grieve what it has lost?',
        'Where am I holding grief at bay that is asking to be acknowledged?',
        'Where in my body do I carry the weight of anticipatory grief?',
        'Where could I create a safe space to let the grief move through me?',
        'Where in my life is there a person or a practice that can hold me while I grieve?',
        'Where am I pretending strength when tenderness is what this moment actually asks for?',
        'Where would allowing the grief to come create more room for love?',
      ],
    },
  },
  {
    id: 16,
    name: 'Forgiveness',
    fullName: 'Knot of Forgiveness',
    theme: 'Setting Down What You Were Never Meant to Carry',
    movement: 'Peace',
    movementNumber: 4,
    knotsTruth: 'Forgiveness is not about making peace with what happened. It is about releasing what still binds you to it.',
    openingQuote: "Forgiveness is not about making peace with what happened. It's about releasing what still binds you to it.",
    anchorQuestions: {
      why: [
        'Why am I able to release what I no longer need to carry, even if it was never resolved?',
        'Why does forgiveness serve me more than it serves anyone else?',
        'Why is letting go not the same as saying what happened was okay?',
        'Why do guilt and resentment cost more than the situation that created them?',
        'Why am I allowed to release the standard of perfection in an impossible situation?',
        'Why does forgiveness free me to be more fully present going forward?',
        'Why is setting something down an act of strength, not surrender?',
      ],
      what: [
        'What becomes possible when I stop holding myself to the standard of perfection in an impossible situation?',
        'What am I still carrying that was never mine to carry?',
        'What would I release if I believed forgiveness was available to me?',
        'What guilt or regret has followed me long past its usefulness?',
        'What resentment am I holding that is quietly costing me peace?',
        'What would change in my daily experience if I set one burden down?',
        'What do I want to stop dragging into the future that belongs only to the past?',
      ],
      where: [
        'Where in my life am I ready to loosen my grip on guilt, regret, or resentment — and choose peace instead?',
        'Where am I still punishing myself for something I could not have done differently?',
        'Where does unforgiveness live in my body, and what does it cost me each day?',
        'Where in a relationship am I holding something that forgiveness could soften?',
        'Where could releasing one grievance today create more freedom to move forward?',
        'Where is the invitation to set something down that I have been treating as permanent?',
        'Where would forgiveness — of myself or another — open a door I have kept closed?',
      ],
    },
  },
  {
    id: 17,
    name: 'Peace',
    fullName: 'Knot of Peace',
    theme: 'The Sea Grows Still',
    movement: 'Peace',
    movementNumber: 4,
    knotsTruth: 'The sea may not always grow still, but something in you can.',
    anchorQuestions: {
      why: [
        'Why am I able to trust peace, even when life remains imperfect and unfinished?',
        'Why does peace not require the resolution of every difficult thing?',
        'Why is inner stillness possible even when outer circumstances remain uncertain?',
        'Why do I deserve to rest in peace before the journey is over?',
        'Why is peace not a reward I earn but a ground I can return to?',
        'Why does choosing peace become easier each time I practice it?',
        'Why am I allowed to be at peace with what I cannot control?',
      ],
      what: [
        'What becomes possible when I stop believing peace must wait until everything is solved?',
        'What would I do differently today if I began from a place of peace rather than urgency?',
        'What is already peaceful in my life that I have been overlooking?',
        'What does peace feel like when it visits me, and how do I recognize it?',
        'What would I let go of today if peace were my highest priority?',
        'What has happened in this journey that I can now hold with more acceptance than before?',
        'What does moving forward with peace, rather than resolution, actually look like?',
      ],
      where: [
        'Where in my life is quiet, acceptance, or rest already trying to find me?',
        'Where do I feel most at peace, and how often am I choosing to go there?',
        'Where could I release the need to figure it all out and simply rest in what is?',
        'Where in my body does peace live when I am not pushing it away?',
        'Where am I making peace conditional on something that may never arrive?',
        'Where is one place I could choose peace today — not because everything is fine, but because I am?',
        'Where does this long journey want to deposit you, and what does that place feel like?',
      ],
    },
  },
];

export const MOVEMENTS = [
  { number: 1, name: 'Awareness', description: 'Recognizing what is true', knotIds: [1, 2, 3, 4, 5] },
  { number: 2, name: 'Embodiment', description: 'Living what you know', knotIds: [6, 7, 8, 9, 10] },
  { number: 3, name: 'Integration', description: 'Weaving it into who you are', knotIds: [11, 12, 13, 14, 15] },
  { number: 4, name: 'Peace', description: 'Arriving home to yourself', knotIds: [16, 17] },
];

export function getKnotById(id: number): KnotData | undefined {
  return KNOTS.find((k) => k.id === id);
}

export function getDayContent(knotId: number, day: number): DayContent {
  const knot = getKnotById(knotId);
  if (!knot) throw new Error(`Knot ${knotId} not found`);

  if (day === 1) {
    return { day, type: 'truth', question: knot.knotsTruth, knotId, knotName: knot.name };
  } else if (day >= 2 && day <= 8) {
    return { day, type: 'why', question: knot.anchorQuestions.why[day - 2], knotId, knotName: knot.name };
  } else if (day >= 9 && day <= 15) {
    return { day, type: 'what', question: knot.anchorQuestions.what[day - 9], knotId, knotName: knot.name };
  } else {
    return { day, type: 'where', question: knot.anchorQuestions.where[day - 16], knotId, knotName: knot.name };
  }
}

export const MOCK_USER: MockUser = {
  id: 'demo-user',
  name: 'Caregiver',
  email: 'demo@example.com',
  progress: {
    currentKnotId: 1,
    currentDay: 5,
    streak: 5,
    totalDaysCompleted: 4,
    completedKnots: [],
    lastCompletedDate: new Date(Date.now() - 86400000).toISOString(),
  },
  journalEntries: [
    {
      id: '1', userId: 'demo-user', knotId: 1, day: 1, dayType: 'truth',
      question: KNOTS[0].knotsTruth,
      response: "Reading this today stopped me cold. I realized how often I move through each day hoping someone will notice — and then telling myself I don't need them to. I do need it. I always have.",
      createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    },
    {
      id: '2', userId: 'demo-user', knotId: 1, day: 2, dayType: 'why',
      question: KNOTS[0].anchorQuestions.why[0],
      response: "Because carrying this alone was never the requirement. I made it the requirement. No one asked me to disappear into this role — I thought it was what love looked like.",
      createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    },
    {
      id: '3', userId: 'demo-user', knotId: 1, day: 3, dayType: 'why',
      question: KNOTS[0].anchorQuestions.why[1],
      response: "I've been so focused on being the caregiver that I forgot I'm also a person with a story worth telling. My experience matters too.",
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: '4', userId: 'demo-user', knotId: 1, day: 4, dayType: 'why',
      question: KNOTS[0].anchorQuestions.why[2],
      response: "I keep minimizing everything I'm going through. 'Other people have it worse.' But my story is still real. My exhaustion is still real. I'm allowed to say that.",
      createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
  ],
};
